name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Build utilities installation
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Package build
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}